!Read in the output data file and Generate an IDL .pro file, with which you can 
!plot a triangle-style plot.
!You can also modify the generated file and make a plot that you prefer.
Module GenerateIDL
	use cosmoSetUp, only : nparam, pset, modelname
	use ReadData, only : obs, nobs
	use Constants, only : mtxt
	use IO

	character, parameter :: c_idx='c'
	character, parameter :: ip_idx='i'
	character, parameter :: x_idx='x'
	character, parameter :: parr_idx='p'
	character(len=mtxt) :: IDLfile
	
	contains


	subroutine GenIDL(useMCMC)
		integer :: useMCMC

		if(useMCMC .eq. 1 ) then 
			IDLfile=trim(modelname)//IDLMCMCfile
			call GenIDL_MCMC
		else
			IDLfile=trim(modelname)//IDLGridfile
			call GenIDL_Grid
		endif
	end subroutine GenIDL
!---------------------------------------------MCMC-------------------------------------------------		
	subroutine GenIDL_MCMC
		use Precision
		implicit none
		integer :: iobs
		integer :: iparam, jparam
		character(len=mtxt) :: obsname, tmp, tmp2 
		integer :: uidl
		uidl=unit_idl
		open(uidl, file=trim(plotdir)//(trim(IDLfile)//'.pro'))
		write(uidl, *)	';Generated by ', trim(version)	
		write(uidl, *) 'pro ', trim(IDLfile), ', usm'
!plotdir=
		write(uidl, *) "plotdir=''"!, trim(plotdir), "'"
		write(uidl, *) "use_multi=usm ;if use_multi=1, &
					plot 'SN', 'SN+Hz', 'SN+Hz+CMB', ..."
		write(uidl, *) ''

!nparam=
		write(uidl, *) trim('nparam=')//ch(nparam)
		write(uidl, *) trim('nobs=')//ch(nobs)
		write(uidl, *) 'npplot=nparam ;or nparam-1 or nparam-2'

!pname=('Om', ..., 'h', 'wb')
		write(uidl, *) "modelname='", trim(modelname), "'"
		write(uidl, *) 'pname=strarr(', ch(nparam), ')', &
						'& precision=fltarr(', ch(nparam), ')'
		do iparam=1, nparam
			write(uidl, *) 'pname(', ch(iparam-1), ")='", trim(pset(iparam)%name)//"'", &
							' &precision(', ch(iparam-1), ')=', pset(iparam)%width 
		end do
!Get a proper magnification factor
		write(uidl, *) 'mag=1./precision'
		write(uidl, *) ''

!Get observation names
	tmp='['
	do iobs=1, nobs
		tmp2="'"
		tmp2=trim(tmp2)//obs(iobs)%name
		tmp2=trim(tmp2)//"'"
		tmp=trim(tmp)//trim(tmp2)
		if(iobs/=nobs) then
			tmp=trim(tmp)//','
		else 
			tmp=trim(tmp)//']'
		endif
	enddo
	write(uidl, *) 'obsname=', trim(tmp)

		write(uidl, *) ';------------------begin plotting-----------------'
		write(uidl, *) "set_plot, 'ps'"
		write(uidl, *) 'loadct, 13, NCOLORS=', num_color
		write(uidl, *) 'cxori=', cxori
		write(uidl, *) 'cyori=', cyori
		write(uidl, *) 'cxend=', cxend
		write(uidl, *) 'cyend=', cyend
		write(uidl, *) 'xgap=', xgap
		write(uidl, *) 'ygap=', ygap
		write(uidl, *) 'csize=', charsize

		write(uidl, *) 'pheight=(cyend-cyori-(npplot-1)*ygap)/npplot'
		write(uidl, *) 'pwidth =(cxend-cxori-(npplot-1)*xgap)/npplot'
		write(uidl, *) 'clvl=[6.18, 2.3]' !, 11.83]'  
		write(uidl, *) 'clvl=exp(-0.5*clvl)'
		write(uidl, *) 'lcolor=50'

		write(uidl, *) 'nc=', num_color
		write(uidl, *) 'maxlvl=7'
		write(uidl, *) 'lglvls=maxlvl-maxlvl*findgen(200+1)/200'
		write(uidl, *) 'lvls=exp(-0.5*lglvls)'
		write(uidl, *) 'colors=lvls*nc'
		write(uidl, *) 'bklvl=min(lvls)'
		write(uidl, *) 'bkcolor=bklvl*nc'

		write(uidl, *) 'obscolor=indgen(nobs)*lcolor'

		write(uidl, *) 'item=', "''"

		write(uidl, *) 'for iobs=0, nobs-1 do begin'
			write(uidl, *) '	if(use_multi eq 1) then begin' 
			write(uidl, *) '		if(iobs eq 0) then item=obsname(iobs)'
			write(uidl, *) "		if(iobs ne 0) then item=item+'_'+obsname(iobs)"
			write(uidl, *) '	endif'
			write(uidl, *) "	if(use_multi ne 1) then item=obsname(iobs)"
			write(uidl, *) '	datname=plotdir+modelname+item+', "'_mc.dat'"
			call multi_index(nparam, c_idx, tmp) !tmp='c1, c2, c3, c4' 
			write(uidl, *) '	readcol, datname, ', trim(tmp)//', chi2' 

			write(uidl, *) 'nsample=size(c1, /n_elements)'
			write(uidl, *) 'ptot=fltarr(nparam, nsample)'
			do iparam=1, nparam
				write(uidl, *) 'ptot(', ch(iparam-1), ', *)=c', ch(iparam)
			end do
			write(uidl, *) 'psname=plotdir+modelname+item+', "'_mc.ps'"
			write(uidl, *) 'device, file=psname, /color'
			write(uidl, *) 'for iparam=0, npplot-1 do begin'
			write(uidl, *) '	for jparam=npplot-1, iparam, -1 do begin'
			write(uidl, *) '		xname=pname(iparam)'
			write(uidl, *) '		yname=pname(jparam)'	
 			write(uidl, *) "		xtkname=''"
 			write(uidl, *) "		ytkname=''"
			write(uidl, *) '		if(jparam ne npplot-1) then begin'
 			write(uidl, *) "			xtkname=replicate(' ', 8)"
 			write(uidl, *) "			xname=''"
 			write(uidl, *) '		endif'  
 			write(uidl, *) '		if(iparam ne 0) then begin'
 			write(uidl, *) "			ytkname=replicate(' ', 8)"
 			write(uidl, *) "			yname=''"
			write(uidl, *) '		endif'
			write(uidl, *) '		pxori=cxori+iparam*(pwidth+xgap)'
			write(uidl, *) '		pyori=cyori+(npplot-1-jparam)*(pheight+ygap)'
			write(uidl, *) '		pxend=pxori+pwidth'
			write(uidl, *) '		pyend=pyori+pheight'
			write(uidl, *) '	    if(iparam eq jparam) then begin'
			write(uidl, *) '			var=ptot(iparam, *)'
			write(uidl, *) '			vplot=(var-min(var))*mag(iparam)'
			write(uidl, *) '			size_bin=1' !bs(iparam).'
			write(uidl, *) '			hist_var=histogram(vplot, binsize=size_bin)'
			write(uidl, *) '			tmp=size(hist_var, /dimensions)'
			write(uidl, *) '			size_var=tmp(0)'
			write(uidl, *) '			xaxis=min(var)+findgen(size_var)*(max(var)-min(var))/(size_var-1)'
			write(uidl, *) '			max_hist=max(hist_var, location)'
			write(uidl, *) '			indmax=array_indices(hist_var, location)'
			write(uidl, *) '			indx=indmax(0)'
			!plot a black box first
			write(uidl, *) '			plot, xaxis, hist_var*1.0/max(hist_var), $'  
			write(uidl, *) '					xtit=xname, charsize=csize,$'
			write(uidl, *) '					position=[pxori, pyori, pxend, pyend], /noerase, /nodata, $'
			write(uidl, *) '					xtickname=xtkname, ystyle=4, xstyle=8'
			write(uidl, *) '			oplot, xaxis, hist_var*1.0/max(hist_var), $'
			write(uidl, *) '					color=lcolor*iobs'
			write(uidl, *) ' 			oplot, [xaxis(indx), xaxis(indx)], $'
		 	write(uidl, *) '					[0, 1], linestyle=2'	
			write(uidl, *) '		endif else begin'
			write(uidl, *) '			vx=ptot(iparam, *)'
			write(uidl, *) '			vy=ptot(jparam, *)'
			write(uidl, *) '			vxplot=(vx-min(vx))*mag(iparam)'
			write(uidl, *) '			vyplot=(vy-min(vy))*mag(jparam)'
			write(uidl, *) '			size_bin1=1' !bs(iparam).'
			write(uidl, *) '			size_bin2=1' !bs(jparam).'
			write(uidl, *) '			hist_var=hist_2d(vxplot, vyplot, bin1=size_bin1, bin2=size_bin2)'
			write(uidl, *) '			hist_var=smooth(hist_var, 3)'
			write(uidl, *) '			tmp=size(hist_var, /dimensions)'
			write(uidl, *) '			svx=tmp(0)'
			write(uidl, *) '			svy=tmp(1)'
			write(uidl, *) '			xaxis=min(vx)+findgen(svx)*(max(vx)-min(vx))/(svx-1)'
			write(uidl, *) '			yaxis=min(vy)+findgen(svy)*(max(vy)-min(vy))/(svy-1)'
			write(uidl, *) '			max_hist=max(hist_var, location)'
			write(uidl, *) '			indmax=array_indices(hist_var, location)'
			write(uidl, *) '			indx=indmax(0) & indy=indmax(1)'
			write(uidl, *) '			contour, bklvl+fltarr(svx, svy), level=bklvl, $'
			write(uidl, *) '				c_color=bkcolor, xaxis, yaxis, /fill, $'
			write(uidl, *) '				position=[pxori, pyori, pxend, pyend], /noerase, $'
			write(uidl, *) '				xtickname=xtkname, ytickname=ytkname, charsize=csize, $'
			write(uidl, *) '				xtit=xname, ytit=yname, xstyle=1, ystyle=1'
			write(uidl, *) '			contour, hist_var*1.0/max(hist_var), xaxis, yaxis, $'
			write(uidl, *) '				level=lvls, /fill, /noerase, $' 
			write(uidl, *) '				c_colors=colors, /overplot'
			write(uidl, *) '			oplot, [xaxis(indx)], [yaxis(indy)],$'
			write(uidl, *) '				 psym=1'	

			write(uidl, *) '		endelse'
			write(uidl, *) '	endfor'
			write(uidl, *) 'endfor'
			write(uidl, *) 'bxori=cxori-0.07'
			write(uidl, *) 'byori=cyori'
			write(uidl, *) 'bxend=cxori-0.06'
			write(uidl, *) 'byend=cyend'
			write(uidl, *) 'bloc=[bxori, byori, bxend, byend]'
			write(uidl, *) 'fsc_colorbar, ncolors=nc, /vertical, position=bloc, $'
			write(uidl, *) "		minrange=0, maxrange=1.0, format='(F4.2)', $"
			write(uidl, *) "		title='Likelihood', charsize=csize"
		!	write(uidl, *) 'position=[lxori, lyori]'
		!    write(uidl, *) 'plot,findgen(11)/10, findgen(11)/10, /noerase, color=300'
		!    write(uidl, *) 'legend, items, color=obscolor,linestyle=0, position=position'
		!	write(uidl, *) "print, 'Plot Over!'"
			write(uidl, *) 'device, /close'	
			write(uidl, *) 'endfor'
		write(uidl, *) "print, 'Plot Over!'"
		write(uidl, *) 'end'
		
		close(uidl)
	end subroutine GenIDL_MCMC
!----------------------------------------------------------------------------------
!----------------------------------------------------------------------------------
!-----------------------------------------Grid-------------------------------------
!----------------------------------------------------------------------------------
!---------------------------------------------------------------------------------- 
	subroutine GenIDL_Grid
		use Precision
		implicit none
		integer :: iparam, iobs, jp
		integer :: uidl
		integer :: idx
		integer, dimension(nparam) :: ibeg, iend
		character(len=mtxt) :: tmp, tmp2, tmp_number
!		character(len=mtxt)	:: mat_idx
		character(len=mtxt)	:: col_idx
		character(len=10)	:: mchi='mchi', lchi='lchi'
		character(len=mtxt) :: psobs

		uidl=unit_idl
		open(uidl, file=trim(plotdir)//(trim(IDLfile)//'.pro'))
		write(uidl, *)	';Generated by ', trim(version)	
		write(uidl, *) 'pro ', trim(IDLfile), ', usm'
		write(uidl, *) "plotdir=''"!, trim(plotdir), "'"
		write(uidl, *) 'use_multi=usm'
		write(uidl, *) ''
!nparam=
		write(uidl, *) trim('nparam=')//ch(nparam)
		write(uidl, *) trim('nobs=')//ch(nobs)
		write(uidl, *) 'npplot=nparam ;or nparam-1 or nparam-2'

!get observation names
	tmp='['
	do iobs=1, nobs
		tmp2="'"
		tmp2=trim(tmp2)//obs(iobs)%name
		tmp2=trim(tmp2)//"'"
		tmp=trim(tmp)//trim(tmp2)
		if(iobs/=nobs) then
			tmp=trim(tmp)//','
		else 
			tmp=trim(tmp)//']'
		endif
	enddo
	write(uidl, *) 'obsname=', trim(tmp)

!pname=('Om', 'f', 'Ophi'...)
		write(uidl, *) "modelname='", trim(modelname), "'"
		write(uidl, *) 'pname=strarr(', ch(nparam), ')'
		do iparam=1, nparam
			write(uidl, *) 'pname(', ch(iparam-1), ")='", trim(pset(iparam)%name)//"'"
		end do

!n1=pset(1)%n etc
		do iparam=1, nparam
			write(tmp, *) pset(iparam)%n
			write(uidl, *) comb_cn('n', iparam), '=', trim(tmp)//'l'
		end do
!readcol, '...\chi2.dat', c1, c2, c3, ..., x1, x2, x3...
		call multi_index(nparam, c_idx, tmp)
		call multi_index(nobs, x_idx, tmp2)

		write(uidl, *) "cname=plotdir+modelname+'", trim(chi2file), "'"
		write(uidl, *) 'readcol, cname, $'
		write(uidl, *) trim(tmp)//',', trim(tmp2)

	write(uidl, *) ';------------get value of each parameter---------'	
!get parameter array
		do iparam=1, nparam
			write(uidl, *) comb_cn(parr_idx, iparam), '=fltarr(', comb_cn('n', iparam), ')'
		enddo	 
		call collum_index(nparam, tmp)
		tmp=trim('(')//tmp
		tmp=trim(tmp)//')'
		do iparam=1, nparam
			do jp=1, nparam
				if(jp/=iparam) write(uidl, *) trim(comb_cn(ip_idx, jp))//'=0'
			end do
			write(uidl, *) 'for ', trim(comb_cn(ip_idx, iparam))//'=0, ', comb_cn('n', iparam), '-1  do begin'
			write(uidl, *)  trim(comb_cn(parr_idx, iparam))//'(', trim(comb_cn(ip_idx, iparam))//')=$'
			write(uidl, *)	trim(comb_cn(c_idx, iparam))//trim(tmp)
			write(uidl, *) 'endfor'
		end do
		
	tmp='ptot=['
	do iparam=1, nparam
		tmp=trim(tmp)//comb_cn(parr_idx, iparam)
		if(iparam/=nparam) then
			tmp=trim(tmp)//',' 
		else
			tmp=trim(tmp)//']'
		endif
	enddo
	write(uidl, *) tmp

	write(uidl, *) trim('ibeg=intarr(')//(trim(ch(nparam))//')')
	write(uidl, *) trim('iend=intarr(')//(trim(ch(nparam))//')')

!idx_p=[0,..,np1-1, np1, ..., np1+np2-1, ...]
	write(uidl, *) ';idx_p=[0,..,np1-1, np1, ..., np1+np2-1, ...]'
	idx=0
	do iparam=1, nparam
		ibeg(iparam)=idx
		idx=idx+pset(iparam)%n
		iend(iparam)=idx-1
	enddo	 
	do iparam=1, nparam
		write(uidl, *) 'ibeg(', ch(iparam-1), ')=', ibeg(iparam)
		write(uidl, *) 'iend(', ch(iparam-1), ')=', iend(iparam)
	enddo


		write(uidl, *) ' '

!mchi=fltarr(nobs, n1*n2*n3...)
		tmp=''
		do iparam=1, nparam
			tmp=trim(tmp)//trim(comb_cn('n', iparam))
			if (iparam/=nparam) then 
				tmp=trim(tmp)//'*'
			else
				tmp=trim(tmp)//')'
			endif
		enddo
		write(uidl, *) 'rawmchi=fltarr(nobs, ', trim(tmp)
!mchi(0, :)=x1; mchi(1, :)=x2; ...
		do iobs=1, nobs
			write(uidl, *) 'rawmchi(', ch(iobs-1), ', *)=', comb_cn(x_idx, iobs)
		enddo

!mchi=fltarr(1, 50, 30, 20)
		do iparam=1, nparam
			if (iparam==1) tmp=trim('mchi=fltarr(')
			tmp=trim(tmp)//comb_cn('n', iparam)
			if(iparam/=nparam) then
				tmp=trim(tmp)//','
			else
				tmp=trim(tmp)//')'	 
			endif
		enddo
		write(uidl, *) tmp
		!write(uidl, *) 'cur_chi=0'
		write(uidl, *) 'cur_chi=0'

!		call multi_index(nparam, ip_idx, mat_idx)
	write(uidl, *) ';------------------begin plotting-----------------'
	write(uidl, *) "set_plot, 'ps'"
	write(uidl, *) 'loadct, 13'
!	write(uidl, *) "device, file='", trim(plotdir)//(trim(psfile)//"', /color")
	write(uidl, *) 'cxori=', cxori
	write(uidl, *) 'cyori=', cyori
	write(uidl, *) 'cxend=', cxend
	write(uidl, *) 'cyend=', cyend
	write(uidl, *) 'xgap=', xgap
	write(uidl, *) 'ygap=', ygap

	write(uidl, *) 'pheight=(cyend-cyori-(npplot-1)*ygap)/npplot'
	write(uidl, *) 'pwidth =(cxend-cxori-(npplot-1)*xgap)/npplot'
	write(uidl, *) 'clvl=[2.3, 6.18]' !, 11.83]'  
	write(uidl, *) 'lcolor=50'
	write(uidl, *) 'obscolor=indgen(nobs)*lcolor'
	write(uidl, *) 'items=obsname'
	write(uidl, *) 'for ', trim('iobs')//'=0, ', ch(nobs-1), ' do begin'
	write(uidl, *) '; ------------get the chi2 matrix: mchi---------------'
	write(uidl, *) '	if (use_multi eq 1) then begin'
	write(uidl, *) ";obsname=['SN', 'SN+Hz', 'SN+Hz+BAO', 'SN+Hz+BAO+BAOP', 'SN+Hz+BAO+BAOP+CMB']"
	write(uidl, *) '		for jobs=0, iobs do begin'
	write(uidl, *) '			if (jobs eq 0) then tmp=obsname(jobs)'
	write(uidl, *) "			if (jobs ne 0) then tmp=tmp+'+'+obsname(jobs)"
	write(uidl, *) '		endfor'
	write(uidl, *) '		items(iobs)=tmp'
	write(uidl, *) '		cur_chi=cur_chi+rawmchi(iobs, *) '
	write(uidl, *) '	endif else begin'
	write(uidl, *) ';		items(iobs)=obsname(iobs)'
	write(uidl, *) '		cur_chi=rawmchi(iobs, *)'
	write(uidl, *) '	endelse'

	write(uidl, *) "fname=plotdir+modelname+items(iobs)+'_grid.ps'"
	write(uidl, *) 'device, file=fname, /color'
!for i1=1, pset(ip)-1'...
		do iparam=1, nparam
			write(uidl, *) '	for ', trim(comb_cn(ip_idx, iparam))//'=0, ', trim(comb_cn('n', iparam))//'-1  do begin'
		end do
		
		call multi_index(nparam, ip_idx, tmp)
		call collum_index(nparam, col_idx)

		tmp=trim('(')//tmp
		tmp=trim(tmp)//')=$'
		write(uidl, '(a5, a)')  '', trim(mchi)//trim(tmp)
		tmp='cur_chi('
		tmp=trim(tmp)//(trim(col_idx)//')')
		write(uidl, *) tmp

!'endfor'...
		do iparam=1, nparam
			write(uidl, *) '	endfor'
		end do

	write(uidl, *) '	min_chi=min(mchi)'
	write(uidl, *) '	mchi=exp((600.0d - 0.5d*(temporary(mchi) - min_chi)) > (-600.0d))'

	write(uidl, *) '	for iparam=0, npplot-1 do begin'
	write(uidl, *) '		for jparam=npplot-1, iparam, -1 do begin'
	write(uidl, *) '			mxtmp=mchi'	
	write(uidl, *) '			xname=pname(iparam)'
	write(uidl, *) '			yname=pname(jparam)'	
 	write(uidl, *) "			xtkname=''"
 	write(uidl, *) "			ytkname=''"
	write(uidl, *) '			if(jparam ne npplot-1) then begin'
 	write(uidl, *) "				xtkname=replicate(' ', 8)"
 	write(uidl, *) "				xname=''"
 	write(uidl, *) '			endif'  
 	write(uidl, *) '			if(iparam ne 0) then begin'
 	write(uidl, *) "				ytkname=replicate(' ', 8)"
 	write(uidl, *) "				yname=''"
	write(uidl, *) '			endif'
	write(uidl, *) '			for kparam=nparam-1, 0, -1 do begin'
	write(uidl, *) '				if (kparam ne iparam && kparam ne jparam) then begin'
	write(uidl, *) '				mxtmp=total(mxtmp, kparam+1)'
	write(uidl, *) '				endif'
	write(uidl, *) '			endfor'
	write(uidl, *) '			mxtmp=-2.*alog(mxtmp)'
	write(uidl, *) '			min_mxtmp=min(mxtmp, location)'
	write(uidl, *) '			indmin=array_indices(mxtmp, location)'
	write(uidl, *) '			mxtmp=mxtmp-min(mxtmp)'
	write(uidl, *) '			pxori=cxori+iparam*(pwidth+xgap)'
	write(uidl, *) '			pyori=cyori+(npplot-1-jparam)*(pheight+ygap)'
	write(uidl, *) '			pxend=pxori+pwidth'
	write(uidl, *) '			pyend=pyori+pheight'
	write(uidl, *) '			if(iparam eq jparam) then begin'
	write(uidl, *) '				indx=indmin(0)' 
	write(uidl, *) '				plot, ptot(ibeg(iparam):iend(iparam)), $'
	write(uidl, *) '					exp(-0.5*mxtmp), xtit=xname, ytit=dChi2, charsize=0.5,$'
	write(uidl, *) '					position=[pxori, pyori, pxend, pyend], /noerase, /nodata, $'
	write(uidl, *) '					xtickname=xtkname ;, ystyle=4, xstyle=8'
	write(uidl, *) '				oplot, ptot(ibeg(iparam):iend(iparam)), $'
	write(uidl, *) '					exp(-0.5*mxtmp), color=lcolor*iobs'
	write(uidl, *) ' 				oplot, [ptot(ibeg(iparam)+indx), ptot(ibeg(iparam)+indx)], $'
 	write(uidl, *) '					[0, 1], linestyle=2'
!	write(uidl, *) '				onesigma=where(abs(mxtmp(ibeg(iparam)+indx:iend(iparam))-1) lt 0.01)'
!	write(uidl, *) '				if (onesigma eq -1)	then $'
!	write(uidl, *) '					onesigma=where(abs(mxtmp(ibeg(iparam)+indx:iend(iparam))-1) lt 0.1)'
!	write(uidl, *) '				sos=size(onesigma, /n_elements)'
!	write(uidl, *) '				uponesig=onesigma(sos-1)'
!	write(uidl, *) '				onesigma=where(abs(mxtmp(ibeg(iparam):ibeg(iparam)+indx)-1) lt 0.01) '
!	write(uidl, *) '				if (onesigma eq -1) then $'
!	write(uidl, *) '					onesigma=where(abs(mxtmp(ibeg(iparam):ibeg(iparam)+indx)-1) lt 0.1) '
!	write(uidl, *) '				dnonesig=onesigma(0)	'
!	write(uidl, *) '				get_lun, /lun'
!	write(uidl, *) "				openu, lun, 'stat.txt'"
!	write(uidl, *) '				printf, lun, pname(iparam), $'
!	write(uidl, *) "					'   - ', mxtmp(ibeg(iparam)+indx)-mxtmp(ibeg(iparam)+dnonesig), $"
!	write(uidl, *) "					'   + ', mxtmp(ibeg(iparam)+indx+uponesig)-mxtmp(ibeg(iparam)+indx)"
!	write(uidl, *) '				free_lun, /lun'
	write(uidl, *) '			endif else begin'
	write(uidl, *) '			indx=indmin(0) & indy=indmin(1)'
	write(uidl, *) '			contour, mxtmp, ptot(ibeg(iparam):iend(iparam)), $'
	write(uidl, *) '						ptot(ibeg(jparam):iend(jparam)), $'
	write(uidl, *) '					 level=clvl, xtit=xname, ytit=yname, $' 
	write(uidl, *) '				c_colors=lcolor*iobs, charsize=0.5, c_linestyle=[0, 1],$'
	write(uidl, *) ' 				xstyle=1, ystyle=1, $'
	write(uidl, *) '				position=[pxori, pyori, pxend, pyend], /noerase, $'
	write(uidl, *) '						xtickname=xtkname, ytickname=ytkname'
	write(uidl, *) '			oplot, [ptot(ibeg(iparam)+indx)], [ptot(ibeg(jparam)+indy)],$'
	write(uidl, *) '				 psym=1, color=lcolor*iobs'	
	write(uidl, *) '			endelse'
	write(uidl, *) '		endfor'
	write(uidl, *) '	endfor' 
	write(uidl, *) '	device, /close'  
	write(uidl, *) 'endfor' 
	write(uidl, *) ';lxori=', lxori
	write(uidl, *) ';lyori=', lyori

	write(uidl, *) ';position=[lxori, lyori]'
    	write(uidl, *) ';plot,findgen(11)/10, findgen(11)/10, /noerase, color=300'
    	write(uidl, *) ';legend, items, color=obscolor,linestyle=0, position=position'
	write(uidl, *) "print, 'Plot Over!'"
		

	write(uidl, *) 'end'
	close(uidl)
	end subroutine GenIDL_Grid

	subroutine multi_index(np, prefix, m_index)
		implicit none
		character(len=mtxt) :: tmp, m_index
		integer :: np, ip
		character :: prefix
		
		m_index=''	
		do ip=1, np
			tmp=ch(ip)
			tmp=trim(prefix)//tmp
			m_index=trim(m_index)//trim(tmp)
			if(ip/=np) m_index=trim(m_index)//','
		enddo		
	end subroutine multi_index

	
	subroutine collum_index(np, c_index)
		implicit none
		integer :: ip, jp, np
		character(len=mtxt) :: c_index, tmp
		c_index=''
		do ip=np, 1, -1
			c_index=trim(comb_cn(ip_idx, ip))//c_index
			do jp=ip+1, np
				tmp=comb_cn('n', jp)
				tmp=trim(tmp)//'*'
				c_index=trim(tmp)//c_index
			enddo
			if(ip/=1) then
				c_index=trim('+')//trim(c_index)
!			else
!				c_index=trim('(')//trim(c_index)
			endif
		enddo
	end subroutine collum_index
		 
	function comb_cn(c, n)
		implicit none
		integer :: n
		character :: c
		character(len=2) :: nc
		character(len=2) :: comb_cn
		nc=ch(n)
		write(nc, '(i1)') n
		comb_cn=trim(c)//trim(nc)
	end function
	
	function ch(n)
		implicit none
		character :: ch
		integer :: n
		write(ch, '(i1)') n
	end function		 
end Module GenerateIDL
